ALTER TABLE book ADD FOREIGN KEY(cid) REFERENCES calssify(cid);
ALTER TABLE details ADD FOREIGN KEY(bid) REFERENCES book(bid);
ALTER TABLE details ADD FOREIGN KEY(oid) REFERENCES orders(oid);
ALTER TABLE orders ADD FOREIGN KEY(uid) REFERENCES USER(uid);
